"""empty message

Revision ID: 246e754b5df8
Revises: 
Create Date: 2021-11-24 22:57:30.403855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246e754b5df8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('subscribers', sa.String(length=20), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('date_uploaded', sa.Date(), nullable=False),
    sa.Column('video_link', sa.String(length=255), nullable=False),
    sa.Column('preview_link', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('channel')
    # ### end Alembic commands ###
