"""empty message

Revision ID: 25aea8c16b6e
Revises: 246e754b5df8
Create Date: 2021-12-05 13:53:04.958991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25aea8c16b6e'
down_revision = '246e754b5df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radio_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('package', sa.String(length=20), nullable=True),
    sa.Column('photo_link', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capacitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radiopart_id', sa.Integer(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['radiopart_id'], ['radio_part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transistor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radiopart_id', sa.Integer(), nullable=True),
    sa.Column('power_dissipation', sa.Float(), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('current', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['radiopart_id'], ['radio_part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transistor')
    op.drop_table('capacitor')
    op.drop_table('radio_part')
    # ### end Alembic commands ###
