"""empty message

Revision ID: 37593d8ddcf8
Revises: 3a47a1c67fa5
Create Date: 2021-12-05 15:35:33.221751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37593d8ddcf8'
down_revision = '3a47a1c67fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('radio_part', sa.Column('manufacturer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'radio_part', 'manufacturer', ['manufacturer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'radio_part', type_='foreignkey')
    op.drop_column('radio_part', 'manufacturer_id')
    op.drop_table('manufacturer')
    # ### end Alembic commands ###
