"""empty message

Revision ID: 3a47a1c67fa5
Revises: 25aea8c16b6e
Create Date: 2021-12-05 15:07:00.182486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a47a1c67fa5'
down_revision = '25aea8c16b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('power_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radiopart_id', sa.Integer(), nullable=True),
    sa.Column('input_voltage', sa.Float(), nullable=False),
    sa.Column('output_voltage', sa.Float(), nullable=False),
    sa.Column('output_current', sa.Float(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['radiopart_id'], ['radio_part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resistor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radiopart_id', sa.Integer(), nullable=True),
    sa.Column('power_dissipation', sa.Float(), nullable=False),
    sa.Column('resistance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['radiopart_id'], ['radio_part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transistor', sa.Column('type', sa.String(length=40), nullable=False))
    op.add_column('transistor', sa.Column('temp', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transistor', 'temp')
    op.drop_column('transistor', 'type')
    op.drop_table('resistor')
    op.drop_table('power_unit')
    # ### end Alembic commands ###
